### ISSUE TITLE
Graph do not resize down correctly

### ISSUE THREAD

**Issue by mathias22osterhagen22** [ecomfe/vue-echarts#658] opened 2022-10-05 14:17 UTC
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
Local version: 
c4w-tailwind@0.0.0
├─┬ @vitejs/plugin-vue@3.0.3
│ └── vue@3.2.37 deduped
├── echarts@5.3.3
├─┬ pinia@2.0.19
│ ├─┬ vue-demi@0.13.8
│ │ └── vue@3.2.37 deduped
│ └── vue@3.2.37 deduped
├─┬ vue-echarts@6.2.3
│ ├── echarts@5.3.3 deduped
│ ├─┬ vue-demi@0.13.11
│ │ └── vue@3.2.37 deduped
│ └── vue@3.2.37 deduped
├─┬ vue-router@4.1.3
│ └── vue@3.2.37 deduped
└─┬ vue@3.2.37
  └─┬ @vue/server-renderer@3.2.37
    └── vue@3.2.37 deduped

Reproduction:
"dependencies": {
    "echarts": "^5.3.3",
    "vue": "^3.2.37",
    "vue-echarts": "^6.2.3"
  },
```

### Details

When the windows is resized UP the graph resize well.
When the windows is resized Down the graph do not resize at all.

[https://user-images.githubusercontent.com/60438474/194082663-ac416a25-782c-4bfb-be18-2108680f50d4.mp4](https://user-images.githubusercontent.com/60438474/194082663-ac416a25-782c-4bfb-be18-2108680f50d4.mp4)

The margin left that you can see pop and unpop on the video represent the open/close triggering of the left navbar in my local project.

Tested under Firefox & Brave.

### Reproduction

https://stackblitz.com/edit/vue-echarts-vue-3-n8wtss?file=src/App.vue

**Comment by Justineo** [comment] 2022-10-18 10:35
https://user-images.githubusercontent.com/1726061/196407381-8ec74447-b3df-4d47-8eae-aadb87e02347.mp4

I cannot reproduce this in Firefox 105. Do you still have this issue?

**Comment by Justineo** [comment] 2022-10-18 11:44
I'm closing this since I cannot reproduce the issue. If you are still experiencing this issue, more information on how to reproduce it is welcome.

**Closed by Justineo** 2022-10-18 11:44 UTC
